CREATE USER IF NOT EXISTS 'analytics'@'localhost' IDENTIFIED BY 'analyticSpec3fic!!';
GRANT SELECT ON openemr.* TO 'analytics'@'localhost';
GRANT ALL PRIVILEGES ON `analytics`.* TO 'analytics'@'localhost';
GRANT SELECT ON analytics.* TO 'rstudio'@'localhost';
GRANT CREATE USER ON *.* TO 'analytics'@'localhost';
GRANT ALL PRIVILEGES ON analytics.* TO 'analytics'@'localhost';
GRANT ALL PRIVILEGES ON `analytics\_%`.* TO 'analytics'@'localhost';
GRANT GRANT OPTION, CREATE USER ON *.* TO 'analytics'@'localhost';
GRANT SELECT ON mysql.db TO 'analytics'@'localhost';
GRANT RELOAD ON *.* TO 'analytics'@'localhost';
GRANT FILE ON *.* TO 'analytics'@'localhost';
FLUSH PRIVILEGES;